spring:
  session:
    store-type: redis
    # timeout: 1800s # 30 minutos
    redis:
      namespace: spring:session
  
  data:
    redis:
      host: deliveryfood-redis
      # port: 6379
      # password: sua-senha
      # username: seu-usuario
      client-type: lettuce # Padrão no Spring Boot 3.x
      lettuce:
        pool:
          enabled: true
          max-active: 8
          max-idle: 8
          min-idle: 0